Fixed Aggregate getTable and updated README.md
shivareddyiirs/QRealTime pull request #68
Opened 2022-02-01 06:05 UTC by ianmahoney1

2022-02-01 23:12 UTC, lognaturel commented on README.md
> +You can install your own aggregate server <a href="http://docs.opendatakit.org/aggregate-guide/"> here </a> <br/>
I recommend replacing this by Central and not linking to Aggregate docs. The plugin support will certainly still be helpful for folks who have existing Aggregate servers but we don't recommend setting up a new one.

A follow-on issue would be to swap the order of the Central and Aggregate tabs in the UI.

2022-02-01 23:12 UTC, lognaturel commented on README.md
> +https://www.youtube.com/watch?v=62oqJE0pgIY
This is great! Make sure to change your password if you haven't already. 😊 A possible follow-up issue would be to show/hide that password.

2022-02-02 11:16 UTC, shivareddyiirs requested changes

2022-02-02 11:16 UTC, shivareddyiirs commented on README.md
> +<br/><br/>If you want to import data from already existing form (created without using our plugin) do ensure that the name of the geometry field is 'GEOMETRY', 'location', or 'gps'. Other geometry fi
Constraint on name of the geometry is no more there. Please verify

2022-02-04 18:31 UTC, ianmahoney1 commented on README.md
> +<br/><br/>If you want to import data from already existing form (created without using our plugin) do ensure that the name of the geometry field is 'GEOMETRY', 'location', or 'gps'. Other geometry fi
Yes this is true. Changed README to reflect this.

2022-02-05 01:35 UTC, merged